FROM node:22-alpine
WORKDIR /app
ENV TZ=Asia/Bangkok
RUN apk add --no-cache tzdata && npm install -g npm@11
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
EXPOSE 3000
CMD ["npm", "run", "dev"]
