alter table public.system_settings
  add column evidence_retention_enabled boolean not null default true,
  add column evidence_retention_days integer not null default 180;

alter table public.system_settings
  add constraint system_settings_evidence_retention_days_check
  check (evidence_retention_days between 30 and 3650);

alter table public.events
  add column evidence_retention_days integer;

alter table public.events
  add constraint events_evidence_retention_days_check
  check (
    evidence_retention_days is null
    or evidence_retention_days = 0
    or evidence_retention_days between 30 and 3650
  );

comment on column public.events.evidence_retention_days is
  'NULL inherits the system setting, 0 keeps evidence forever, otherwise 30-3650 days.';

alter table public.submissions
  add column evidence_size_bytes bigint,
  add column evidence_deleted_at timestamptz,
  add column evidence_delete_reason text;

alter table public.submissions
  add constraint submissions_evidence_size_bytes_check
  check (evidence_size_bytes is null or evidence_size_bytes >= 0),
  add constraint submissions_evidence_delete_reason_check
  check (
    evidence_delete_reason is null
    or evidence_delete_reason in ('retention', 'manual')
  );

update public.submissions as submissions
set evidence_size_bytes = (objects.metadata ->> 'size')::bigint
from storage.objects as objects
where objects.bucket_id = 'run-evidence'
  and objects.name = submissions.evidence_url
  and objects.metadata ->> 'size' ~ '^[0-9]+$'
  and submissions.evidence_size_bytes is null;

create index submissions_retained_evidence_registration_idx
  on public.submissions (registration_id, created_at)
  where evidence_url is not null and status in ('approved', 'rejected');

create table public.evidence_cleanup_runs (
  id bigint generated by default as identity primary key,
  requested_by uuid references public.users(id) on delete set null,
  event_id uuid references public.events(id) on delete set null,
  source text not null check (source in ('manual', 'cron')),
  retention_days integer,
  matched_files integer not null default 0 check (matched_files >= 0),
  deleted_files integer not null default 0 check (deleted_files >= 0),
  reclaimed_bytes bigint not null default 0 check (reclaimed_bytes >= 0),
  failed_files integer not null default 0 check (failed_files >= 0),
  failure_summary text,
  created_at timestamptz not null default now()
);

alter table public.evidence_cleanup_runs enable row level security;

revoke all on table public.evidence_cleanup_runs from public, anon, authenticated, service_role;
grant select, insert on table public.evidence_cleanup_runs to service_role;
revoke all on sequence public.evidence_cleanup_runs_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.evidence_cleanup_runs_id_seq to service_role;

create index evidence_cleanup_runs_created_idx
  on public.evidence_cleanup_runs (created_at desc);

create or replace function public.get_evidence_cleanup_candidates(
  p_event_id uuid default null,
  p_limit integer default 500,
  p_today date default current_date
)
returns table (
  submission_id uuid,
  evidence_path text,
  evidence_size_bytes bigint,
  event_id uuid,
  event_title text,
  event_end_date date,
  retention_days integer
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    submissions.id,
    submissions.evidence_url,
    submissions.evidence_size_bytes,
    events.id,
    events.title,
    events.end_date,
    coalesce(events.evidence_retention_days, settings.evidence_retention_days)
  from public.submissions as submissions
  join public.registrations as registrations
    on registrations.id = submissions.registration_id
  join public.events as events
    on events.id = registrations.event_id
  cross join public.system_settings as settings
  where settings.id = 1
    and settings.evidence_retention_enabled
    and submissions.evidence_url is not null
    and submissions.status in ('approved', 'rejected')
    and coalesce(events.evidence_retention_days, settings.evidence_retention_days) > 0
    and events.end_date
      + coalesce(events.evidence_retention_days, settings.evidence_retention_days)
      <= p_today
    and (p_event_id is null or events.id = p_event_id)
  order by events.end_date, submissions.created_at, submissions.id
  limit least(greatest(coalesce(p_limit, 500), 1), 1000);
$$;

revoke all on function public.get_evidence_cleanup_candidates(uuid, integer, date)
  from public, anon, authenticated, service_role;
grant execute on function public.get_evidence_cleanup_candidates(uuid, integer, date)
  to service_role;

create or replace function public.get_evidence_retention_summary(
  p_today date default current_date
)
returns table (
  event_id uuid,
  event_title text,
  event_title_en text,
  event_end_date date,
  event_retention_days integer,
  retention_days integer,
  eligible boolean,
  evidence_files bigint,
  evidence_bytes bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    events.id,
    events.title,
    events.title_en,
    events.end_date,
    events.evidence_retention_days,
    coalesce(events.evidence_retention_days, settings.evidence_retention_days),
    settings.evidence_retention_enabled
      and coalesce(events.evidence_retention_days, settings.evidence_retention_days) > 0
      and events.end_date
        + coalesce(events.evidence_retention_days, settings.evidence_retention_days)
        <= p_today,
    count(submissions.id) filter (
      where submissions.evidence_url is not null
        and submissions.status in ('approved', 'rejected')
    ),
    coalesce(sum(submissions.evidence_size_bytes) filter (
      where submissions.evidence_url is not null
        and submissions.status in ('approved', 'rejected')
    ), 0)
  from public.events as events
  cross join public.system_settings as settings
  left join public.registrations as registrations
    on registrations.event_id = events.id
  left join public.submissions as submissions
    on submissions.registration_id = registrations.id
  where settings.id = 1
    and events.end_date < p_today
  group by
    events.id,
    events.title,
    events.title_en,
    events.end_date,
    events.evidence_retention_days,
    settings.evidence_retention_enabled,
    settings.evidence_retention_days
  order by events.end_date desc, events.id;
$$;

revoke all on function public.get_evidence_retention_summary(date)
  from public, anon, authenticated, service_role;
grant execute on function public.get_evidence_retention_summary(date)
  to service_role;
