-- Harden submission creation against concurrent duplicate/daily-limit bypasses,
-- add application-level rate limiting, and retain an immutable admin review log.

do $$
begin
  if exists (
    select 1
    from public.submissions
    where normalized_sha256 is not null
    group by normalized_sha256
    having count(*) > 1
  ) then
    raise exception 'Cannot enforce normalized evidence uniqueness: duplicate hashes already exist';
  end if;
end
$$;

drop index if exists public.submissions_normalized_sha256_idx;

create unique index submissions_normalized_sha256_key
  on public.submissions (normalized_sha256)
  where normalized_sha256 is not null;

alter table public.submissions
  drop constraint if exists submissions_duplicate_match_type_check;

alter table public.submissions
  add constraint submissions_duplicate_match_type_check
    check (
      duplicate_match_type is null
      or duplicate_match_type in ('exact', 'normalized', 'perceptual', 'activity')
    ),
  add column activity_fingerprint text,
  add column reviewed_by uuid references public.users(id) on delete set null,
  add column reviewed_at timestamptz,
  add column review_note text,
  add constraint submissions_activity_fingerprint_format_check
    check (activity_fingerprint is null or activity_fingerprint ~ '^[0-9a-f]{64}$'),
  add constraint submissions_review_note_length_check
    check (review_note is null or char_length(review_note) <= 2000);

update public.submissions
set activity_fingerprint = encode(
  extensions.digest(
    concat_ws(
      '|',
      'v1',
      activity_type,
      activity_local_date::text,
      to_char(distance_km, 'FM999990.00'),
      coalesce(duration_sec, 0)::text
    ),
    'sha256'
  ),
  'hex'
)
where activity_fingerprint is null;

update public.submissions
set review_note = 'Legacy approval before duplicate reason enforcement',
    reviewed_at = coalesce(reviewed_at, created_at)
where status = 'approved'
  and duplicate_match_type in ('normalized', 'perceptual')
  and nullif(btrim(review_note), '') is null;

alter table public.submissions
  alter column activity_fingerprint set not null,
  add constraint submissions_duplicate_approval_reason_check
    check (
      status <> 'approved'
      or duplicate_match_type is null
      or duplicate_match_type not in ('normalized', 'perceptual')
      or char_length(btrim(coalesce(review_note, ''))) >= 10
    );

create index submissions_user_activity_fingerprint_idx
  on public.submissions (user_id, activity_fingerprint);

create index submissions_reviewed_by_idx
  on public.submissions (reviewed_by)
  where reviewed_by is not null;

create table public.submission_rate_limit_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  ip_hash text not null check (ip_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now()
);

alter table public.submission_rate_limit_attempts enable row level security;

create index submission_rate_limit_user_created_idx
  on public.submission_rate_limit_attempts (user_id, created_at desc);

create index submission_rate_limit_ip_created_idx
  on public.submission_rate_limit_attempts (ip_hash, created_at desc);

create index submission_rate_limit_created_idx
  on public.submission_rate_limit_attempts (created_at);

revoke all on table public.submission_rate_limit_attempts from public, anon, authenticated, service_role;
grant select, insert, delete on table public.submission_rate_limit_attempts to service_role;
revoke all on sequence public.submission_rate_limit_attempts_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.submission_rate_limit_attempts_id_seq to service_role;

create table public.submission_review_audit (
  id bigint generated by default as identity primary key,
  submission_id uuid not null references public.submissions(id) on delete cascade,
  reviewer_id uuid references public.users(id) on delete set null,
  previous_status text not null
    check (previous_status in ('approved', 'pending', 'flagged', 'rejected')),
  new_status text not null
    check (new_status in ('approved', 'pending', 'flagged', 'rejected')),
  review_note text check (review_note is null or char_length(review_note) <= 2000),
  created_at timestamptz not null default now()
);

alter table public.submission_review_audit enable row level security;

create index submission_review_audit_submission_created_idx
  on public.submission_review_audit (submission_id, created_at desc);

create index submission_review_audit_reviewer_idx
  on public.submission_review_audit (reviewer_id)
  where reviewer_id is not null;

revoke all on table public.submission_review_audit from public, anon, authenticated, service_role;
grant select, insert on table public.submission_review_audit to service_role;
revoke all on sequence public.submission_review_audit_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.submission_review_audit_id_seq to service_role;

create or replace function public.consume_submission_rate_limit(
  p_user_id uuid,
  p_ip_hash text,
  p_user_limit integer default 5,
  p_ip_limit integer default 20,
  p_window_seconds integer default 600
)
returns text
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_window_start timestamptz;
begin
  if p_user_id is null
    or p_ip_hash !~ '^[0-9a-f]{64}$'
    or p_user_limit not between 1 and 100
    or p_ip_limit not between 1 and 500
    or p_window_seconds not between 60 and 86400
  then
    raise exception 'invalid_submission_rate_limit_input';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('submission-rate-user:' || p_user_id::text, 0));
  perform pg_advisory_xact_lock(hashtextextended('submission-rate-ip:' || p_ip_hash, 0));

  v_window_start := clock_timestamp() - make_interval(secs => p_window_seconds);

  delete from public.submission_rate_limit_attempts
  where created_at < clock_timestamp() - interval '1 day';

  if (
    select count(*)
    from public.submission_rate_limit_attempts
    where user_id = p_user_id
      and created_at >= v_window_start
  ) >= p_user_limit then
    return 'user_limit';
  end if;

  if (
    select count(*)
    from public.submission_rate_limit_attempts
    where ip_hash = p_ip_hash
      and created_at >= v_window_start
  ) >= p_ip_limit then
    return 'ip_limit';
  end if;

  insert into public.submission_rate_limit_attempts (user_id, ip_hash)
  values (p_user_id, p_ip_hash);

  return 'allowed';
end;
$$;

revoke all on function public.consume_submission_rate_limit(uuid, text, integer, integer, integer)
  from public, anon, authenticated;
grant execute on function public.consume_submission_rate_limit(uuid, text, integer, integer, integer)
  to service_role;

create or replace function public.create_guarded_submission(
  p_registration_id uuid,
  p_user_id uuid,
  p_source text,
  p_activity_type text,
  p_distance_km numeric,
  p_duration_sec integer,
  p_activity_date timestamptz,
  p_activity_local_date date,
  p_flag_reason text[],
  p_activity_fingerprint text,
  p_strava_activity_id text default null,
  p_evidence_url text default null,
  p_evidence_sha256 text default null,
  p_normalized_sha256 text default null,
  p_evidence_phash text default null,
  p_ocr_status text default 'not_processed',
  p_ocr_distance_km numeric default null,
  p_ocr_confidence numeric default null,
  p_ocr_raw_text text default null,
  p_ocr_processed_at timestamptz default null,
  p_phash_max_distance integer default 10
)
returns table (
  submission_id uuid,
  submission_status text,
  duplicate_type text,
  duplicate_submission_id uuid,
  duplicate_distance integer
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_daily_limit integer;
  v_existing_count integer;
  v_flag_reason text[] := coalesce(p_flag_reason, array[]::text[]);
  v_duplicate_type text;
  v_duplicate_submission_id uuid;
  v_duplicate_distance integer;
  v_status text;
  v_submission_id uuid;
begin
  if p_source not in ('upload', 'strava')
    or p_activity_type not in ('run', 'walk')
    or p_distance_km is null
    or p_distance_km <= 0
    or p_duration_sec is null
    or p_duration_sec <= 0
    or p_activity_date is null
    or p_activity_local_date is null
    or p_activity_fingerprint !~ '^[0-9a-f]{64}$'
  then
    raise exception 'invalid_submission_input';
  end if;

  if not exists (
    select 1
    from public.registrations as registrations
    join public.packages as packages on packages.id = registrations.package_id
    where registrations.id = p_registration_id
      and registrations.user_id = p_user_id
      and registrations.status = 'confirmed'
      and p_activity_type = any(packages.activity_types)
  ) then
    raise exception 'invalid_confirmed_registration';
  end if;

  if p_source = 'upload' and (
    p_evidence_url is null
    or p_evidence_sha256 !~ '^[0-9a-f]{64}$'
    or p_normalized_sha256 !~ '^[0-9a-f]{64}$'
    or p_evidence_phash !~ '^[0-9a-f]{16}$'
    or p_ocr_status not in ('matched', 'mismatch', 'unreadable', 'error')
  ) then
    raise exception 'invalid_upload_evidence';
  end if;

  if p_source = 'strava' and nullif(btrim(p_strava_activity_id), '') is null then
    raise exception 'missing_strava_activity_id';
  end if;

  if p_source = 'upload' then
    -- The global near-match lock is held only for the short database section.
    perform pg_advisory_xact_lock(hashtextextended('submission-evidence-near-match', 0));

    if exists (
      select 1 from public.submissions where evidence_sha256 = p_evidence_sha256
    ) then
      raise unique_violation using message = 'duplicate_evidence_exact';
    end if;

    if exists (
      select 1 from public.submissions where normalized_sha256 = p_normalized_sha256
    ) then
      raise unique_violation using message = 'duplicate_evidence_normalized';
    end if;
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      'submission-day:' || p_registration_id::text || ':' || p_activity_local_date::text,
      0
    )
  );

  select coalesce(system_settings.submission_daily_limit, 3)
  into v_daily_limit
  from public.system_settings as system_settings
  where system_settings.id = 1;

  v_daily_limit := coalesce(v_daily_limit, 3);

  select count(*)::integer
  into v_existing_count
  from public.submissions
  where registration_id = p_registration_id
    and activity_local_date = p_activity_local_date;

  if v_existing_count >= v_daily_limit
    and not ('daily_submission_limit_exceeded' = any(v_flag_reason))
  then
    v_flag_reason := array_append(v_flag_reason, 'daily_submission_limit_exceeded');
  end if;

  if p_source = 'upload' then
    select submissions.id
    into v_duplicate_submission_id
    from public.submissions as submissions
    where submissions.user_id = p_user_id
      and submissions.activity_fingerprint = p_activity_fingerprint
    order by submissions.created_at, submissions.id
    limit 1;

    if found then
      v_duplicate_type := 'activity';
      v_duplicate_distance := 0;
    else
      select near_match.submission_id, near_match.distance
      into v_duplicate_submission_id, v_duplicate_distance
      from public.find_near_duplicate_evidence(p_evidence_phash, p_phash_max_distance) as near_match
      limit 1;

      if found then
        v_duplicate_type := 'perceptual';
      end if;
    end if;
  end if;

  v_status := case
    when cardinality(v_flag_reason) = 0
      and v_duplicate_type is null
      and (p_source = 'strava' or p_ocr_status = 'matched')
    then 'approved'
    else 'flagged'
  end;

  insert into public.submissions (
    registration_id, user_id, source, activity_type, distance_km, duration_sec,
    activity_date, activity_local_date, flag_reason, activity_fingerprint,
    strava_activity_id, evidence_url, evidence_sha256, normalized_sha256,
    evidence_phash, duplicate_match_type, duplicate_match_submission_id,
    duplicate_similarity_distance, ocr_status, ocr_distance_km, ocr_confidence,
    ocr_raw_text, ocr_processed_at, status
  ) values (
    p_registration_id, p_user_id, p_source, p_activity_type, p_distance_km,
    p_duration_sec, p_activity_date, p_activity_local_date, v_flag_reason,
    p_activity_fingerprint, p_strava_activity_id, p_evidence_url,
    p_evidence_sha256, p_normalized_sha256, p_evidence_phash,
    v_duplicate_type, v_duplicate_submission_id, v_duplicate_distance,
    p_ocr_status, p_ocr_distance_km, p_ocr_confidence, p_ocr_raw_text,
    p_ocr_processed_at, v_status
  )
  returning id into v_submission_id;

  return query
  select
    v_submission_id,
    v_status,
    v_duplicate_type,
    v_duplicate_submission_id,
    v_duplicate_distance;
end;
$$;

revoke all on function public.create_guarded_submission(
  uuid, uuid, text, text, numeric, integer, timestamptz, date, text[], text,
  text, text, text, text, text, text, numeric, numeric, text, timestamptz, integer
) from public, anon, authenticated;
grant execute on function public.create_guarded_submission(
  uuid, uuid, text, text, numeric, integer, timestamptz, date, text[], text,
  text, text, text, text, text, text, numeric, numeric, text, timestamptz, integer
) to service_role;

create or replace function public.log_submission_review_change()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.status is distinct from old.status
    or new.reviewed_by is distinct from old.reviewed_by
    or new.review_note is distinct from old.review_note
  then
    insert into public.submission_review_audit (
      submission_id,
      reviewer_id,
      previous_status,
      new_status,
      review_note
    ) values (
      new.id,
      new.reviewed_by,
      old.status,
      new.status,
      new.review_note
    );
  end if;
  return new;
end;
$$;

revoke all on function public.log_submission_review_change() from public, anon, authenticated;

create trigger submissions_review_audit_trigger
  after update of status, reviewed_by, review_note on public.submissions
  for each row execute function public.log_submission_review_change();

create or replace function public.review_submission_guarded(
  p_submission_id uuid,
  p_reviewer_id uuid,
  p_status text,
  p_review_note text default null
)
returns table (
  submission_id uuid,
  previous_status text,
  submission_status text,
  registration_id uuid,
  user_id uuid,
  distance_km numeric
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_submission public.submissions%rowtype;
  v_previous_status text;
  v_note text := nullif(btrim(p_review_note), '');
begin
  if p_status not in ('approved', 'pending', 'rejected') then
    raise exception 'invalid_review_status';
  end if;

  if not exists (
    select 1
    from public.users
    where id = p_reviewer_id
      and role in ('super_admin', 'admin', 'staff')
  ) then
    raise exception 'reviewer_not_authorized';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('submission-review:' || p_submission_id::text, 0));

  select *
  into v_submission
  from public.submissions
  where id = p_submission_id
  for update;

  if not found then
    raise exception 'submission_not_found';
  end if;

  if p_status = 'approved'
    and v_submission.duplicate_match_type in ('normalized', 'perceptual')
    and char_length(coalesce(v_note, '')) < 10
  then
    raise exception 'duplicate_approval_reason_required';
  end if;

  if v_note is not null and char_length(v_note) > 2000 then
    raise exception 'review_note_too_long';
  end if;

  v_previous_status := v_submission.status;

  update public.submissions
  set status = p_status,
      reviewed_by = p_reviewer_id,
      reviewed_at = clock_timestamp(),
      review_note = v_note
  where id = p_submission_id
  returning * into v_submission;

  perform public.sync_submission_distance_points(
    p_submission_id,
    p_status = 'approved'
  );

  return query
  select
    v_submission.id,
    v_previous_status,
    v_submission.status,
    v_submission.registration_id,
    v_submission.user_id,
    v_submission.distance_km;
end;
$$;

revoke all on function public.review_submission_guarded(uuid, uuid, text, text)
  from public, anon, authenticated;
grant execute on function public.review_submission_guarded(uuid, uuid, text, text)
  to service_role;
